spring.application.name=week8

spring.datasource.url=jdbc:mariadb://localhost:3306/ironhack
spring.datasource.username=danial
spring.datasource.password=enter


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.profiles.active=demo
